### ISSUE TITLE
unit gets removed if 'clip' is used

### ISSUE THREAD

**Issue by ascii-husky** [unionco/scss-slope-calc#1]
if flag 'clip' is used then the value for the highest ('clipped') breakpoint has no unit and isn't valid.

For Example
```css
.element{
    @include slope-calc(margin, 40px 375px, 50px 1920px, clip);
}
```

compiles to:

```css
@media only screen and (min-width: 120em){
.element {
    margin: 50; //missing 'px'
}
}
.element {
    margin: calc(0.64725vw + 2.3483rem);
}
```
Thanks!
